services:
  hello-perld:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /usr/src/myapp
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: